#!/usr/bin/env python3
"""Update source_registry.json with all 41 approved PDFs."""

import json
from pathlib import Path
from datetime import datetime, timedelta

# All 41 approved PDFs with metadata
APPROVED_SOURCES = [
    # WHO/Official (5)
    {
        "filename": "9789240003910-eng.pdf",
        "source_id": "WHO_Stress_Management_Guide",
        "organization": "World Health Organization",
        "year": 2024,
        "title": "Stress Management and Well-being",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": ["crisis_intervention"],
        "clinical_risk": "low",
    },
    {
        "filename": "23-MH-8110-Understanding-Psychosis.pdf",
        "source_id": "WHO_Psychosis_Guide",
        "organization": "World Health Organization",
        "year": 2023,
        "title": "Understanding Psychosis",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": ["crisis_intervention"],
        "clinical_risk": "medium",
    },
    {
        "filename": "FS_GriefInAdults_EN_2025.pdf",
        "source_id": "WHO_Grief_Factsheet",
        "organization": "World Health Organization",
        "year": 2025,
        "title": "Grief in Adults - Fact Sheet",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": ["crisis_intervention"],
        "clinical_risk": "low",
    },
    {
        "filename": "surgeon-general-social-connection-advisory.pdf",
        "source_id": "US_SG_Social_Connection",
        "organization": "US Surgeon General",
        "year": 2023,
        "title": "Social Connection and Public Health Advisory",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": ["crisis_intervention"],
        "clinical_risk": "low",
    },
    {
        "filename": "clinical-research-trials-you-questions-answers.pdf",
        "source_id": "Clinical_Trials_Guide",
        "organization": "Clinical Research Resources",
        "year": 2023,
        "title": "Clinical Trials: Questions and Answers",
        "evidence_level": "educational",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index", "methodology_index"],
        "not_allowed": ["crisis_intervention"],
        "clinical_risk": "low",
    },

    # Clinical Manuals & Workbooks (4)
    {
        "filename": "EMOTION REGULATION SKILLS MANUAL.pdf",
        "source_id": "Emotion_Regulation_Skills",
        "organization": "Clinical Resources",
        "year": 2024,
        "title": "Emotion Regulation Skills Manual",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["coping_strategy", "psychoeducation"],
        "allowed_indexes": ["coping_skills_index", "psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "DISTRESS TOLERANCE SKILLS MANUAL e-version.pdf",
        "source_id": "Distress_Tolerance_Skills",
        "organization": "Clinical Resources",
        "year": 2024,
        "title": "Distress Tolerance Skills Manual",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["coping_strategy", "psychoeducation"],
        "allowed_indexes": ["coping_skills_index", "safety_crisis_index"],
        "not_allowed": [],
        "clinical_risk": "medium",
    },
    {
        "filename": "rtp_unit-2-workbook.pdf",
        "source_id": "RTP_Training_Workbook",
        "organization": "Training Resources",
        "year": 2023,
        "title": "Resilience Training Program Workbook",
        "evidence_level": "educational",
        "allowed_use": ["coping_strategy", "psychoeducation"],
        "allowed_indexes": ["coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "tips-for-talking-with-a-health-care-provider-about-your-mental-health_1.pdf",
        "source_id": "Healthcare_Communication",
        "organization": "Clinical Resources",
        "year": 2023,
        "title": "Tips for Talking with Healthcare Providers",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },

    # Turkish Sources (3)
    {
        "filename": "turkpsikoloji.1515430.pdf",
        "source_id": "Turkish_Psychology_Journal",
        "organization": "Turkish Psychological Association",
        "year": 2023,
        "title": "Turkish Psychology Journal Article",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "resiliencepsikolojik-dayaniklilik.pdf",
        "source_id": "Turkish_Resilience_Guide",
        "organization": "Turkish Psychology Resources",
        "year": 2023,
        "title": "Psikolojik Dayanıklılık (Resilience)",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index", "coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "1002672446-schoka.pdf",
        "source_id": "Turkish_Mental_Health",
        "organization": "Turkish Clinical Resources",
        "year": 2023,
        "title": "Turkish Mental Health Guide",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },

    # High-Quality Research Papers (23)
    {
        "filename": "annurev-psych-010418-102813.pdf",
        "source_id": "Annual_Review_Psychology",
        "organization": "Annual Reviews",
        "year": 2018,
        "title": "Annual Review of Psychology - Peer-Reviewed Research",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "methodology"],
        "allowed_indexes": ["psychoeducation_index", "methodology_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Attachment Style and Dissolution of Romantic Relationships.pdf",
        "source_id": "Attachment_Research",
        "organization": "Academic Research",
        "year": 2020,
        "title": "Attachment Styles in Romantic Relationships",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Anxiety_Sensitivity_and_Catastrophizing.pdf",
        "source_id": "Anxiety_Research",
        "organization": "Academic Research",
        "year": 2021,
        "title": "Anxiety Sensitivity and Catastrophic Thinking",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Emotion_Regulation_through_Cognitive_Strategies.pdf",
        "source_id": "Emotion_Regulation_Research",
        "organization": "Academic Research",
        "year": 2021,
        "title": "Emotion Regulation through Cognitive Strategies",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index", "coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Emotion_regulation.pdf",
        "source_id": "Emotion_Regulation_Review",
        "organization": "Academic Research",
        "year": 2020,
        "title": "Emotion Regulation: Theory and Practice",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index", "coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Implications of Rejection Sensitivity for Intimate Relationships.pdf",
        "source_id": "Rejection_Sensitivity_Research",
        "organization": "Academic Research",
        "year": 2019,
        "title": "Rejection Sensitivity in Relationships",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Psychology_of_Loneliness.pdf",
        "source_id": "Loneliness_Research",
        "organization": "Academic Research",
        "year": 2018,
        "title": "Psychology of Loneliness",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Self-Esteem, Social Comparison, and Facebook Use.pdf",
        "source_id": "Social_Media_Wellbeing",
        "organization": "Academic Research",
        "year": 2019,
        "title": "Social Media and Self-Esteem",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Self-Compassion, Self-Esteem, and Well-Being.pdf",
        "source_id": "Self_Compassion_Research",
        "organization": "Academic Research",
        "year": 2020,
        "title": "Self-Compassion and Well-Being",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index", "coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Self-harm and PTSD among a sample of women in Turkey the role of self.pdf",
        "source_id": "Turkish_PTSD_Research",
        "organization": "Academic Research",
        "year": 2021,
        "title": "Self-Harm and PTSD in Turkish Population",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index", "safety_crisis_index"],
        "not_allowed": [],
        "clinical_risk": "high",
    },
    {
        "filename": "repetitive-negative-thinking-rumination.pdf",
        "source_id": "Rumination_Research",
        "organization": "Academic Research",
        "year": 2020,
        "title": "Rumination and Repetitive Negative Thinking",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "baumeister and leary.pdf",
        "source_id": "Belonging_Motivation",
        "organization": "Academic Research",
        "year": 1995,
        "title": "The Need to Belong: Motivation and Psychology",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Isolation-and-loneliness-an-overview-of-literature.pdf",
        "source_id": "Isolation_Loneliness_Review",
        "organization": "Academic Research",
        "year": 2022,
        "title": "Isolation and Loneliness: Literature Review",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Avoiding more than Intimacy_ Avoidant Attachment and the Avoidanc.pdf",
        "source_id": "Avoidant_Attachment",
        "organization": "Academic Research",
        "year": 2019,
        "title": "Avoidant Attachment Patterns",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Thinking Errors and Self Defeating Beliefs-Anxiety and Depression.pdf",
        "source_id": "Cognitive_Distortions",
        "organization": "Clinical Resources",
        "year": 2022,
        "title": "Cognitive Distortions and Thinking Errors",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Cognitive-Distortions.pdf",
        "source_id": "Cognitive_Errors_Guide",
        "organization": "Clinical Resources",
        "year": 2021,
        "title": "Cognitive Distortions Guide",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "cognitive-distortions (2).pdf",
        "source_id": "Cognitive_Patterns",
        "organization": "Clinical Resources",
        "year": 2021,
        "title": "Recognizing Cognitive Distortion Patterns",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Body Image - How we think and feel about our bodies.pdf",
        "source_id": "Body_Image_Guide",
        "organization": "Clinical Resources",
        "year": 2022,
        "title": "Body Image and Self-Perception",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "Learned-Helplessness.pdf",
        "source_id": "Learned_Helplessness",
        "organization": "Academic Research",
        "year": 2020,
        "title": "Learned Helplessness Theory",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "HO15_ThnkngAbtThnkng.pdf",
        "source_id": "Metacognition_Guide",
        "organization": "Clinical Resources",
        "year": 2021,
        "title": "Thinking About Thinking: Metacognition",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "post-traumatic-stress-disorder_1.pdf",
        "source_id": "PTSD_Guide",
        "organization": "Clinical Resources",
        "year": 2023,
        "title": "Understanding Post-Traumatic Stress Disorder",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index", "safety_crisis_index"],
        "not_allowed": [],
        "clinical_risk": "high",
    },
    {
        "filename": "Trauma-Informed-Behaviour-Support-A-Practical-Guide-to-Developing-Resilient-Learners-1673306765.pdf",
        "source_id": "Trauma_Informed_Support",
        "organization": "Educational Resources",
        "year": 2022,
        "title": "Trauma-Informed Behavior Support",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["coping_skills_index", "safety_crisis_index"],
        "not_allowed": [],
        "clinical_risk": "high",
    },
    {
        "filename": "helping-children-and-adolescents-cope-with-traumatic-events.pdf",
        "source_id": "Childhood_Trauma_Support",
        "organization": "NIMH",
        "year": 2020,
        "title": "Helping Youth Cope with Trauma",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["coping_skills_index", "safety_crisis_index"],
        "not_allowed": [],
        "clinical_risk": "high",
    },
    {
        "filename": "social-anxiety-challenging-anxious-thinking.pdf",
        "source_id": "Social_Anxiety_CBT",
        "organization": "Clinical Resources",
        "year": 2022,
        "title": "Social Anxiety: Challenging Anxious Thoughts",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation", "coping_strategy"],
        "allowed_indexes": ["psychoeducation_index", "coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
    {
        "filename": "perinatal-depression.pdf",
        "source_id": "Perinatal_Mental_Health",
        "organization": "Clinical Resources",
        "year": 2023,
        "title": "Perinatal Depression: Support and Treatment",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "high",
    },
    {
        "filename": "FS_GriefInAdults_EN_2025.pdf",
        "source_id": "Grief_Support",
        "organization": "World Health Organization",
        "year": 2025,
        "title": "Grief in Adults: Support and Understanding",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "medium",
    },
    {
        "filename": "obsessive-compulsive-disorder-508.pdf",
        "source_id": "OCD_Guide",
        "organization": "Clinical Resources",
        "year": 2022,
        "title": "Understanding Obsessive-Compulsive Disorder",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "medium",
    },
    {
        "filename": "bipolar-disorder.pdf",
        "source_id": "Bipolar_Disorder_Guide",
        "organization": "Clinical Resources",
        "year": 2023,
        "title": "Bipolar Disorder: Understanding and Managing",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["psychoeducation"],
        "allowed_indexes": ["psychoeducation_index"],
        "not_allowed": [],
        "clinical_risk": "high",
    },
    {
        "filename": "Fundamentals-of-Psychological-Disorders.pdf",
        "source_id": "Psych_Disorders_Textbook",
        "organization": "Academic Resources",
        "year": 2022,
        "title": "Fundamentals of Psychological Disorders",
        "evidence_level": "educational",
        "allowed_use": ["psychoeducation", "methodology"],
        "allowed_indexes": ["psychoeducation_index", "methodology_index"],
        "not_allowed": [],
        "clinical_risk": "medium",
    },
    {
        "filename": "stand-up-to-stress-coloring-activity-book.pdf",
        "source_id": "Stress_Management_Activities",
        "organization": "Wellness Resources",
        "year": 2022,
        "title": "Stand Up to Stress: Activities for Coping",
        "evidence_level": "clinical_self_help",
        "allowed_use": ["coping_strategy"],
        "allowed_indexes": ["coping_skills_index"],
        "not_allowed": [],
        "clinical_risk": "low",
    },
]

# Index definitions (same as before)
INDEXES = [
    {
        "name": "psychoeducation_index",
        "description": "Educational content on mental health topics",
        "primary_use": "psychoeducation",
        "crisis_isolation": False,
        "min_evidence_level": "educational",
    },
    {
        "name": "coping_skills_index",
        "description": "Practical techniques, exercises, and skills",
        "primary_use": "coping_strategy",
        "crisis_isolation": False,
        "min_evidence_level": "clinical_self_help",
    },
    {
        "name": "safety_crisis_index",
        "description": "Crisis support, safety planning, emergency resources",
        "primary_use": "crisis",
        "crisis_isolation": True,
        "min_evidence_level": "clinical_self_help",
    },
    {
        "name": "methodology_index",
        "description": "Technical documentation and RAG methodology",
        "primary_use": "methodology",
        "crisis_isolation": False,
        "min_evidence_level": "educational",
    },
]

def update_registry():
    """Update source_registry.json with all 41 approved PDFs."""
    registry_path = Path("/Users/aykutakkus/Desktop/Projects/Capstone/data/source_registry.json")

    # Add common metadata
    next_review = (datetime.now() + timedelta(days=365)).date().isoformat()
    approval_date = datetime.now().date().isoformat()

    for source in APPROVED_SOURCES:
        source["approval_date"] = approval_date
        source["next_review"] = next_review
        source["review_status"] = "approved"

    # Build registry
    registry = {
        "version": "2.0",
        "created": approval_date,
        "approval_policy": {
            "require_registry_approval": True,
            "reject_unregistered_sources": True,
            "require_annual_review": True,
            "crisis_isolation_mandatory": True,
        },
        "indexes": INDEXES,
        "sources": APPROVED_SOURCES,
    }

    # Save
    with open(registry_path, "w") as f:
        json.dump(registry, f, indent=2)

    print(f"Updated source_registry.json with {len(APPROVED_SOURCES)} approved PDFs")
    print(f"Saved to: {registry_path}")


if __name__ == "__main__":
    update_registry()
